# Generated by Django 5.2.16 on 2026-07-23 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('module', models.CharField(help_text='Ex: members, ministries, cells, worship, finance, events, scheduling, visitors', max_length=50, verbose_name='módulo')),
                ('action', models.CharField(help_text='Ex: view, create, edit, delete, manage_members', max_length=50, verbose_name='ação')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.churchrole', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'permissão de perfil',
                'verbose_name_plural': 'permissões de perfis',
                'ordering': ['role', 'module', 'action'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('role', 'module', 'action'), name='unique_role_permission')],
            },
        ),
    ]
