# Generated by Django 5.2.15 on 2026-06-22 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=255, verbose_name='nome da família')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
            ],
            options={
                'verbose_name': 'família',
                'verbose_name_plural': 'famílias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='identificador')),
                ('color', models.CharField(blank=True, default='#6B7280', max_length=7, verbose_name='cor (hex)')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='nome completo')),
                ('social_name', models.CharField(blank=True, max_length=255, verbose_name='nome social')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro'), ('uninformed', 'Não informado')], default='uninformed', max_length=12, verbose_name='sexo')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='foto')),
                ('spiritual_status', models.CharField(choices=[('visitor', 'Visitante'), ('decided', 'Decidido'), ('baptizing', 'Batizando'), ('member', 'Membro'), ('leader', 'Líder')], db_index=True, default='visitor', max_length=12, verbose_name='status espiritual')),
                ('conversion_date', models.DateField(blank=True, null=True, verbose_name='data de decisão')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='data de batismo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='consente tratamento de dados')),
                ('consent_communications', models.BooleanField(default=False, verbose_name='consente comunicações')),
                ('consent_date', models.DateTimeField(blank=True, null=True, verbose_name='data do consentimento')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.family', verbose_name='família')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='usuário (login)')),
                ('tags', models.ManyToManyField(blank=True, related_name='members', to='members.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'membro',
                'verbose_name_plural': 'membros',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='family',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_families', to='members.member', verbose_name='responsável'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['spiritual_status', 'is_active'], name='members_mem_spiritu_078c73_idx'),
        ),
    ]
