# Generated by Django 5.2.16 on 2026-07-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='contato de emergência'),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone de emergência'),
        ),
        migrations.AddField(
            model_name='member',
            name='has_special_needs',
            field=models.BooleanField(default=False, verbose_name='possui necessidades especiais?'),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viúvo(a)'), ('uninformed', 'Não informado')], default='uninformed', max_length=12, verbose_name='estado civil'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_since',
            field=models.DateField(blank=True, null=True, verbose_name='membro desde'),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=120, verbose_name='profissão'),
        ),
        migrations.AddField(
            model_name='member',
            name='special_needs_detail',
            field=models.TextField(blank=True, verbose_name='detalhes das necessidades'),
        ),
    ]
