# Generated by Django 5.2.16 on 2026-07-23 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_member_emergency_contact_member_emergency_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='identificador')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('category', models.CharField(choices=[('worship', 'Louvor'), ('children', 'Infantil'), ('youth', 'Jovens'), ('couples', 'Casais'), ('women', 'Mulheres'), ('men', 'Homens'), ('social', 'Ação Social'), ('prayer', 'Intercessão'), ('teaching', 'Ensino/Discipulado'), ('communication', 'Comunicação'), ('reception', 'Recepção'), ('arts', 'Artes (Teatro/Dança)'), ('other', 'Outro')], db_index=True, default='other', max_length=20, verbose_name='categoria')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ministries/photos/', verbose_name='foto/capa')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='data de fundação')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_ministries', to='members.member', verbose_name='líder')),
                ('vice_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_led_ministries', to='members.member', verbose_name='vice-líder')),
            ],
            options={
                'verbose_name': 'ministério',
                'verbose_name_plural': 'ministérios',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MinistryMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('role', models.CharField(blank=True, help_text='Ex: Violonista, Professor 3-5 anos, Coordenador', max_length=120, verbose_name='função')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('away', 'Afastado'), ('leave', 'Licença')], db_index=True, default='active', max_length=10, verbose_name='status')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='data de entrada')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_memberships', to='members.member', verbose_name='membro')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ministries.ministry', verbose_name='ministério')),
            ],
            options={
                'verbose_name': 'membro de ministério',
                'verbose_name_plural': 'membros de ministérios',
                'ordering': ['ministry', 'member__full_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('ministry', 'member'), name='unique_ministry_member')],
            },
        ),
    ]
