# Generated by Django 5.2.15 on 2026-06-23 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=255, verbose_name='nome da célula')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('day_of_week', models.CharField(choices=[('monday', 'Segunda-feira'), ('tuesday', 'Terça-feira'), ('wednesday', 'Quarta-feira'), ('thursday', 'Quinta-feira'), ('friday', 'Sexta-feira'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], db_index=True, max_length=10, verbose_name='dia da semana')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='horário')),
                ('capacity', models.PositiveSmallIntegerField(default=20, verbose_name='capacidade (pessoas)')),
                ('is_public', models.BooleanField(default=True, verbose_name='visível no mapa')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('co_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coled_cells', to='members.member', verbose_name='co-líder')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_cells', to='members.member', verbose_name='líder')),
            ],
            options={
                'verbose_name': 'célula',
                'verbose_name_plural': 'células',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CellAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('meeting_date', models.DateField(db_index=True, verbose_name='data da reunião')),
                ('present', models.BooleanField(default=True, verbose_name='presente')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='cells.cell', verbose_name='célula')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_attendances', to='members.member', verbose_name='membro')),
            ],
            options={
                'verbose_name': 'presença em célula',
                'verbose_name_plural': 'presenças em células',
                'ordering': ['-meeting_date'],
                'constraints': [models.UniqueConstraint(fields=('member', 'cell', 'meeting_date'), name='uq_attendance_member_cell_date')],
            },
        ),
        migrations.CreateModel(
            name='CellMeeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('date', models.DateField(db_index=True, verbose_name='data da reunião')),
                ('report', models.TextField(blank=True, verbose_name='relatório')),
                ('attendance_count', models.PositiveSmallIntegerField(default=0, verbose_name='presentes')),
                ('new_visitors', models.PositiveSmallIntegerField(default=0, verbose_name='visitantes novos')),
                ('decisions', models.PositiveSmallIntegerField(default=0, verbose_name='decisões')),
                ('notes', models.TextField(blank=True, verbose_name='anotações do líder')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='cells.cell', verbose_name='célula')),
            ],
            options={
                'verbose_name': 'relatório de célula',
                'verbose_name_plural': 'relatórios de células',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('cell', 'date'), name='uq_meeting_cell_date')],
            },
        ),
    ]
