# Generated by Django 5.2.16 on 2026-07-23 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('venue_type', models.CharField(choices=[('sports_court', 'Quadra Poliesportiva'), ('soccer_field', 'Campo de Futebol'), ('volleyball', 'Quadra de Vôlei'), ('basketball', 'Quadra de Basquete'), ('bbq_area', 'Área de Churrasco'), ('hall', 'Salão de Festas'), ('playground', 'Parquinho'), ('other', 'Outro')], default='sports_court', max_length=20, verbose_name='tipo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacidade (pessoas)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='localização')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/', verbose_name='foto')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requer aprovação')),
                ('max_hours_per_booking', models.PositiveSmallIntegerField(default=4, verbose_name='horas máx. por reserva')),
                ('min_days_advance', models.PositiveSmallIntegerField(default=1, verbose_name='dias mín. de antecedência')),
            ],
            options={
                'verbose_name': 'espaço/quadra',
                'verbose_name_plural': 'espaços/quadras',
                'ordering': ['venue_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenueBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('title', models.CharField(max_length=255, verbose_name='título do evento')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('date', models.DateField(db_index=True, verbose_name='data')),
                ('start_time', models.TimeField(verbose_name='horário de início')),
                ('end_time', models.TimeField(verbose_name='horário de término')),
                ('contact_name', models.CharField(max_length=120, verbose_name='responsável')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('attendees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='número de participantes')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=15, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_bookings', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_bookings', to='ministries.ministry', verbose_name='ministério')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.venue', verbose_name='espaço')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-date', 'start_time'],
                'indexes': [models.Index(fields=['venue', 'date'], name='venues_venu_venue_i_04a376_idx'), models.Index(fields=['status'], name='venues_venu_status_78f5d4_idx')],
            },
        ),
    ]
