# Generated by Django 5.2.16 on 2026-07-23 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('body', models.TextField(verbose_name='mensagem')),
                ('recipient_type', models.CharField(choices=[('all_members', 'Todos os membros'), ('all_visitors', 'Todos os visitantes'), ('everyone', 'Todos (membros + visitantes)'), ('by_ministry', 'Por ministério'), ('by_status', 'Por status espiritual'), ('by_tag', 'Por tag'), ('by_cell', 'Por célula'), ('custom_list', 'Lista personalizada')], default='all_members', max_length=20, verbose_name='tipo de destinatário')),
                ('recipient_data', models.JSONField(blank=True, default=dict, help_text='IDs selecionados por categoria (ministry_ids, tag_ids, cell_ids, status_list)', verbose_name='filtro de destinatários')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falhou')], db_index=True, default='draft', max_length=15, verbose_name='status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='agendado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='total de destinatários')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='enviados com sucesso')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='falhas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
