# Generated by Django 5.2.16 on 2026-07-23 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='identificador')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('event_type', models.CharField(choices=[('service', 'Culto'), ('prayer_meeting', 'Reunião de Oração'), ('conference', 'Conferência'), ('youth', 'Jovens'), ('women', 'Mulheres'), ('men', 'Homens'), ('children', 'Infantil'), ('social', 'Ação Social'), ('training', 'Treinamento'), ('other', 'Outro')], default='other', max_length=20, verbose_name='tipo')),
                ('recurrence', models.CharField(choices=[('none', 'Não se repete'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('biweekly', 'Quinzenalmente'), ('monthly', 'Mensalmente')], default='none', max_length=15, verbose_name='recorrência')),
                ('start_date', models.DateTimeField(db_index=True, verbose_name='data e hora de início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='data e hora de término')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='local')),
                ('address', models.TextField(blank=True, verbose_name='endereço')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/', verbose_name='imagem/banner')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone do contato')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='vagas')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ministries.ministry', verbose_name='ministério organizador')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'is_active'], name='events_even_start_d_06f960_idx'), models.Index(fields=['event_type', 'is_active'], name='events_even_event_t_4a7262_idx')],
            },
        ),
    ]
