# Generated by Django 5.2.16 on 2026-07-23 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_member_emergency_contact_member_emergency_phone_and_more'),
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='nome completo')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('visit_date', models.DateField(db_index=True, verbose_name='data da visita')),
                ('how_found', models.CharField(choices=[('friend', 'Amigo/Parente'), ('social_media', 'Redes Sociais'), ('website', 'Site da Igreja'), ('passing_by', 'Passou em frente'), ('event', 'Evento'), ('other', 'Outro')], default='other', max_length=15, verbose_name='como conheceu')),
                ('how_found_detail', models.CharField(blank=True, max_length=255, verbose_name='detalhe')),
                ('wants_cell', models.BooleanField(default=False, verbose_name='quer participar de célula?')),
                ('follow_up_stage', models.CharField(choices=[('new', 'Novo — aguardando 1º contato'), ('contacted', '1º contato realizado'), ('cell_invited', 'Convidado para célula'), ('service_invited', 'Convidado para culto'), ('converted', 'Convertido a membro'), ('inactive', 'Não respondeu')], db_index=True, default='new', max_length=20, verbose_name='etapa do follow-up')),
                ('first_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='1º contato em')),
                ('cell_invite_at', models.DateTimeField(blank=True, null=True, verbose_name='convite célula em')),
                ('service_invite_at', models.DateTimeField(blank=True, null=True, verbose_name='convite culto em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('converted_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_origin', to='members.member', verbose_name='convertido para membro')),
                ('interested_ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_visitors', to='ministries.ministry', verbose_name='ministério de interesse')),
            ],
            options={
                'verbose_name': 'visitante',
                'verbose_name_plural': 'visitantes',
                'ordering': ['-visit_date'],
            },
        ),
    ]
